/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Orrik (https://sketchfab.com/Orrik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pineapple-5aa21c96319f44e487491ea23bae6d3c
Title: Pineapple
*/

import React, { useRef, useEffect, forwardRef, useImperativeHandle } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame, useThree} from '@react-three/fiber'
import PineappleModel from '../assets/3d/pineapple.glb'
import {a} from '@react-spring/three'
const Pineapple = forwardRef(({scale,position, updatePineapplePosition, ...props}, ref) => {
  const { nodes, materials } = useGLTF(PineappleModel);
  const initialPositionY = useRef(position[1]); // Stocker la position initiale




  useFrame(({clock}) => {
    if (ref.current) {
      const elapsedTime = clock.getElapsedTime()*1.5;
      // Rotation continue
      ref.current.rotation.y += 0.02;
      //ref.current.rotation.x += 0.001; 
    
      // Lévitation (mouvement sinusoïdal)
      ref.current.position.y = initialPositionY.current + Math.sin(elapsedTime) * 0.3;//
      updatePineapplePosition(ref.current.position);
        }

  }); 


  return (
    <a.group ref={ref} position={position} scale={[scale, scale, scale]} {...props}>
      <group scale={[2.921, 3.76, 3.045]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[1.577, 0.987, 2.824]}
        rotation={[-0.408, 0.492, 0.019]}
        scale={[0.104, 0.105, 0.015]}>
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials['Material.003']}
        position={[0.173, 3.11, 0.003]}
        rotation={[-0.077, 0.657, 0.086]}
        scale={[0.589, 1.065, 0.622]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials['Material.004']}
        position={[0.066, 3.563, 0.09]}
        scale={[0.894, 0.167, 0.847]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials['Material.005']}
        position={[0.075, 0.051, 2.99]}
        rotation={[-0.027, 0, -Math.PI / 2]}
        scale={[0.046, 0.046, 0.013]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials['Material.008']}
        position={[1.324, 0.378, 3.458]}
        scale={[0.404, 0.192, 0.032]}
      />
    </a.group>
  )
})

export default Pineapple
